### ISSUE TITLE
Remove Ender Blast from Primed

### ISSUE THREAD

**Issue by TNTTurtles** [OvercastNetwork/Rotations#243]
I know the map was put in a few days ago, but really the gameplay is tedious.

Gravity blocks make the map a team spleef war and ruin gameplay, BY A LOT.

**Comment by HIVERaven** [comment]
This map is still in rotations, and still plays very poorly. @Mikeg542 @ItsMiiOlly Can we get it's rating on the form from the forums please? Current rating network wide is 3.72, but if we look at the ratings from the last month or so (idk if it's possible) I expect it will be significantly lower.

**Comment by Ipskie** [comment]
@HIVERaven why do you expect that? 
Bye I asked bean and he said he'd rather keep it in for now. TBH a rework is no currently in the works but it can be I people are dissatisfied enough

**Comment by HIVERaven** [comment]
@Ipskie I have a theory that it was rated extremely high in the first month or so and had trailed off since, as it is becoming a huge objective farm. Regardless, as seen in cratain's post: https://oc.tc/forums/topics/54bf861ec296352c070000d7 ratings are not that important, gameplay is more so. With all due respect to you as a map maker, the map plays horribly for primed, and is the perfect example of a map where cannons are pointless and tnt running thrives.

**Comment by Ipskie** [comment]
Bean has consented to having it removed, it's already gone. This can be closed
