### ISSUE TITLE
Add Donut Wars

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [OvercastNetwork/Rotations#292]
Now that Donut Wars is finally added to the map repo, it can now be considered for rotations.  I think that the Donut should be bigger or possibly lower the amount of players before being added to rotations.

**Comment by thestrangeboy1** [comment]
Whiskey cannons do so much damage on this map and there's a bit of supplies on the outside part of it. The monuments are so easy to destroy as well. I don't see how this map plays well in a cannoning environment. The outside parts of the map is what you'd want to cannon but it's gets demolished in just a few cannon shots because of how small the width is. Supply chests tend to get blown up quickly from TNT rushers too which makes a match one sided.
