### ISSUE TITLE
Remove Boom from Rotations

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Rotations#328]
The map has great gameplay and nice aesthetics. It's small and appealing to the eye in almost every aspect. 

However, the matches are way too short. Looking in for example Mini03: https://oc.tc/matches?server=Mini03, you can see that the common Boom-match doesn't last longer then 2 minutes, 3 maybe at max. 
It's the easiest way to get multiple objectives in a short period of time. You just walk to the TNT spawners, walk back to wherever you are able to pillar up to the higher levels, make the 10-blocks-long bridge (which is with common bridging techniques way to easy to do), place the TNT in a pyramid, light them and walk over your enemy spawn to the next to reproduce. And then you have gotten 2 monuments, which should take way longer to get normally, in 2 minutes.

Don't get me wrong, the map is great, and the TE version of it (not very different from the original) is great..., though that is where it basically ends. The map can't hold stand in a public match, where defending is no common thought. And what if you try to defend, enemies can build mini chaoses these days to shoot across the void gap, also they can bridge from the end of the lane, pillar up from below, and come from behind. 

The map doesn't work with public play, I'd say it should be removed from the rotations.

**Comment by Tapetepato** [comment]
big +1

**Comment by thestrangeboy1** [comment]
The map rating of 3.60 is like on the chopping block. I would 100% want to remove this map. I don't think the idea of "fast paced" matches are good, I mean what can you really do in about a minute and 30 seconds? Pretty sure every experience player already knows how to rush this constantly with icarusing and there's no way to defend the monument at all because there's no water and you can attack the monument in multiple ways. It's floating in the air too, so that's way harder to defend. Longest match I've ever seen on this was about 4 minutes.

**Comment by matic0basle** [comment]
I like the map but I think it plays a lot better in tournament matches. I wouldn't want to see it go though.

**Comment by Ipskie** [comment]
Still +1 to removal. If not at least reorient the map so that the EW differences are fixed

**Comment by Mikeg542** [comment]
I agree with removal. I don't consider it 'fast-paced', but rather just too fast with objectives far far too easy to get.

**Comment by thestrangeboy1** [comment]
Removed.
