### ISSUE TITLE
Remove Nostalgia

### ISSUE THREAD

**Issue by mrapple** [OvercastNetwork/Rotations#336]
It has served it's course. The maps are consistently among the lowest rated. Primed has become the new place for regulars to hang out and it's constantly improving. I think it's about time we put the bad boy down.

Forum Thread: https://oc.tc/forums/topics/549ce8b5c29635a97b003843

**Comment by Tapetepato** [comment]
Just wondering, but, when is it being removed? Sorry if it takes long to do it, i dont know how this stuff works

**Comment by mrapple** [comment]
This issue was opened for discussion

**Comment by Ipskie** [comment]
I take it then that nostalgia will stay?

**Comment by ItsMiiOlly** [comment]
Correct

**Comment by Tapetepato** [comment]
why will it stay?

**Comment by skippy369** [comment]
@Tapetepato Don't continue to try to remove somethings others may enjoy. As you can hopefully tell the backlash will not be pretty.

**Comment by CoWinkKeyDinkInc** [comment]
@Tapetepato Maybe if people actually know what to do they can actually win against donor stacking for once.  You are complaining simply because one team has brains and one doesn't.

**Comment by Tapetepato** [comment]
@CoWinkKeyDinkInc But that's basically the way Nostalgia plays. Some tourney team or group of 5+ friends jump in, stack, rush, spawnkill and thats it. The team that "has no brains" as you say won't even learn how to cannon, how to defend, etc, if on the first 1-2 minutes they get 5v1ed and then spawnkilled as they respawn. It's just broken and nobody plays there anymore except for these guys that stack. trust me, just randomly jump on Nostalgia, there will be at least 1 guy rushing while the other players are clueless

**Comment by koipen** [comment]
@CoWinkKeyDinkInc It's not about having brains or not. It's about whether you have played for a week or a year. PGM has a huge amount of strategies that for old players are self-evident, but which new players have no chance of knowing. They haven't yet learned them from experience with older players like you have. This gap in knowledge and the advantage a team receives from it is a fact.

Saying they "don't have brains" is incredibly ignorant and insulting. New players are just as smart as anyone else  - they only lack the experience. The problem here is your own elitism.

**Comment by CoWinkKeyDinkInc** [comment]
If people care about winning, they will observe and find a way.  Some people don't even try.

**Comment by mrapple** [comment]
And you still can't see past your own elitism. Wow. 

This discussion is done.
