### ISSUE TITLE
Replace Corrupted Kingdoms on Alpha/Beta to after The Nile

### ISSUE THREAD

**Issue by DoomRobotBoy** [OvercastNetwork/Rotations#347]
Corrupted Kingdoms is a great map. As in appearance as - sort of - in gameplay. The map gives itself a good player flow throughout the map. 

However, since the larger servers get less player-counts the larger maps are suffering from it (as you might know). On CK I think that this problem is worst. The map gives 3 monuments, from which 2 are at easy-to-rush locations. The Hillside and Harbor Monument. Experienced regulars can easily farm these for knowing the positions of the monuments. Most new players cannot see the monument's locations once spawned, that's why these monuments are hardly ever defended.

So I thought that maybe it would be good to move it over to after The Nile. The Nile being a map that a 50/50 chance of getting a long match, could benefit CK as well:

- CK currently average lasting matches is around: 5 minutes. The Nile lasts averagely 50 minutes, with a doubled (sometimes tripled) player count. 
- Another advantage is that the map played before CK in Alpha's rotation can only hold 72 players, while CK can hold 140. The Nile is closer to that 140 with a 100 max.

If not, I suggest improving (doubt that's gonna happen) or removing this map, since its a pretty good farming map, and we shouldn't be supporting obj. farms tbh.

**Comment by itsmartin** [comment]
Never seen a game on CK that didn't end much too fast. Usually 2 monuments are gone within the first few minutes and then the third tends to fall shortly after due to a lack of defence. New players have trouble finding the monuments, especially harbour which is surrounded by buildings and hillside which is off the beaten track.

The suggested updates (beacons to signify monuments, remove hillside, makr harbour more prominent) would definitely help.

**Comment by Tapetepato** [comment]
+1, this map doesn't play how its supposed to play

**Comment by Electroid** [comment]
Not relevant anymore.
