### ISSUE TITLE
Remove Boombox.

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#348]
I made an issue about this around 2-3 months ago and last said that he was going to rebalance it, but it hasnt happened. A/D + TNT just doesnt work. Doesn´t matter what defenders do, this map is basicly designed to painloop. Most of the people dont know how to cannon so usually theres at least 2-3 people on each match that know how to do a basic whiskey (unless its one of those stacked matches with like 7 donors on each team). But doesn't matter how many cannon or bowing you do, usually theres a donor or just some experienced player in attackers that fast bridge and its really difficult to make a cannon every 2-3 blocks of the map to take them out. Theres also the dispensers. Abused by people on both teams very often: Either on attackers to get an easy objective without defense and killfarm, or by defenders, just to spawnkillfarm.
Yes, you can delay them by shooting some bridges, but you cant shoot them all. Almost all the attackers bridge to the side islands or to the dropping tubes.
Once they get near to your base (one of those dropping tubes) they will get more than 60% in a couple of minutes, and 99-100 some minutes later.
Since you cant directly water it, the objective is big and goes throught the 3 floors of the map, attackers can easily bridge from their dropping tubes, and run painlooping around hoping to not get shot. Once they are there, they sneak behind the ice pillar and spam it with tnt, usually as said before, getting some crazy percentages of one run (sometimes even 100%)
It really different to defend because you gotta be watching bridgers, making water walls to prevent whiskeys from the side islands or dispenser cannons from their base, and do this on all 3 floors of them map, While attackers get to your base all the time, since theres nothing to do on their base so they just painloop.
The side islands are barely used by defenders and are often rushed by attackers, allowing them to cannon the pillar easily.
Also, the fact that they get twice the attack damage of defenders its just dumb. Its difficult enough to shoot some of them off and prevent them from getting more than half of the pillar on the first 5 minutes, and this just make them able to 2-3 hit you.
Overall, the map is broken and it just doesn't play well. Unless it gets a really big update changing almost everything from the map, i doubt this will ever play balanced enough to have fun.

**Comment by Tapetepato** [comment]
Its rated like that because attackers is usually with some painloopy objective farmer, and of course, if attackers win they will rate 5 because they ended it in 5-10 minutes and 1 hit killed everyone.

**Comment by DoomRobotBoy** [comment]
It's discussable. I mean the map plays better then half of the Primed maps, though it being a A/D it will always need balancing. Since strategies develop, upgrade, improve, etc. And most of those strategies are in advantage of attackers. I mean you can improve the speed at which you make sky bridges, make cannons, water drop tubes, etc. While the defenders can only repeat their same defenses over and over, and try to cannon enemies away, the attackers can actually improve.

And after BiaB, the strategies for attacking on BoomBox have developed a lot. BoomBox usually ends in a win for the Attackers. Something that could happen, attacking being you don't have to defend or look after an objective. However, if you see this map as a Red vs Blue instead of an Attackers Vs. Defenders, then isn't it a bit weird Red always wins?

**Comment by statcoman** [comment]
The defenders can easily defend if they work together.  Before there was a
melon blockage at the Attacker's spawn it was very hard to defend the
monument because of the fact that the attackers were able to get to the
side pillers before the defenders could even get there themselves.
