### ISSUE TITLE
Add Khaba 

### ISSUE THREAD

**Issue by ParaSpider** [OvercastNetwork/Rotations#352]
This is a very open map with lots of freedom and fun. You can actually have very intense PvP battles as it's easy to pick off certain players. The map looks, and plays, great, and has several fun features including but not limited to the snowballs and double jump. Each player can also impact the game, using things such as snowballs to edit the map. 

It's a very smooth map (no lag, I get very high frames) and it's a high quality map, seeming to be an actual classic that's mixed with the new waves of PGM features without being bad. No improvements currently come to mind, however I believe it's worthy.

More testing certainly needed, but I'm dropping it here for now.

**Comment by Electroid** [comment]
I really like this map :+1:

**Comment by ItsMiiOlly** [comment]
Samsies

**Comment by HIVERaven** [comment]
Can you link me the Map thread?

**Comment by matic0basle** [comment]
I've seen this. At first I though Chick gave up and made a random map because its all flat and the buildings kind of just repeat themselves but after reading the OP with grenades and those special features I kind of like the map. 

I'd say before adding it to rotations setnext it a couple times on some servers where it fits and see what others think of it in chat.

But yeah an interesting map. Wouldn't hurt if its on rotations unless its really hated by players.

**Comment by ParaSpider** [comment]
![](http://i.gyazo.com/0ec263909af5067dd0906187d7ff56e6.png)

https://oc.tc/forums/posts/54a88b6d5f35b9e0c70085b1

**Comment by chickolympics** [comment]
I'm gonna look at lowering the team sizes back down to 16v16 so it would fit in better in mini servers, also it may be slightly less chaotic

**Comment by Avaleer** [comment]
Yes please :D

**Comment by DoomRobotBoy** [comment]
The map has great special gameplay, but it's incredibly chaotic. I can't tell if its TDM or Primed because of the grenade overkill. 

I suggest you move the grenades over to the killrewards. You can even give the players 4 grenades on their first kill, but please not on spawning. Most of the fights I experienced on Khaba I got grenades thrown in my face, something that made the map boring pretty fast.

If the chaos calms down, with for example moving the grenades, I'd say it's good enough to be added.

**Comment by HIVERaven** [comment]
@DoomRobotBoy This would not be a primed map.

**Comment by DoomRobotBoy** [comment]
@HIVERaven it was joke

**Comment by CoWinkKeyDinkInc** [comment]
The double jump restore time should take longer, it is way too easy to chase a person when you can easily pounce at 'em.

**Comment by itsmartin** [comment]
Was a bit chaotic when I played it with 32v32, but still great fun. With 16v16 I think it would probably play well. Would be good to see it in rots.

**Comment by nygiants10** [comment]
This map plays even better than it did originally now that team sizes are 16v16. Khaba is /sned more than any map I've ever seen, sometimes 2-3 times in a row, usually because people are begging to play it again and again. Games always fill up to 30+ people, and many donors play it too, showing that it is popular among experienced and non-experienced players. I would love to see Khaba put into several rotations, and I think many others would too.

**Comment by Electroid** [comment]
Fast paced, exciting, fun, and people seem to love it. It's currently the 3rd highest map rated. Of course this may sway after being in rotations; however, it will get a generous debut. It may be reduced later if need be.

**Comment by HIVERaven** [comment]
It's really fast paced, I think the time should be shortened to 7 or 8 minutes instead of 15. Right now it's long for a TDM, but when you factor in the super fast paced gameplay and the destructive terrain, it plays style wise almost like a rage TDM, but with more action. 15 minutes is too long, half of that would suit it and the rest of the rotation better,

**Comment by Buo111** [comment]
Dude, I love this map with a passion. :heart:
