### ISSUE TITLE
Remove Woolirium

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Rotations#354]
***TNT*** - The map features TNT. While there might not be a lot of it, most of the games I played in the past its just used for team grief. People igniting it in the iron area or at frontlines. I have never seen it be used for good like blowing up a skybridge or defending because defending is quite rare on that map and the TNT is taken before theres a use for it to blow up a skybridge or something like that.
***Defending*** - Defending is not encouraged enough on the map. The possition of the spawn makes it so players just pass the lanes leading to wool rooms. Players will go straight to the iron and then fronlines because they would have to go to the sides and back to get to the wool room. The placement of the wool rooms and the spawn area just does not encourage defending that well. I played at least 10 matches on the map already and I've seen a minimalistic defence on the map once, other matches there was no defence.
***Block spam*** - The map has way too many blocks in the spawn kit. Players block spam right when they get out of spawn. The block spam continues around the frontlines and then over bridges. There should be extra supplies somewhere on the map for defenders but having a total of 4 stacks of planks and a stack of bars in your inventory is too much for a map this size.

***Ratings*** - With the new maps page we can now see the ratings without asking a map developer. This makes it easier for me to post this here. The maps ratings are on the edge with 3.54. 

The map is good when you are playing with friends because theres communication and possibly some of you defend but without communication between the team this map plays quite bad and should be removed.

**Comment by DoomRobotBoy** [comment]
I agree with its removal. 

**TNT and Wool room gear**
Several times I've seen defenses - even the most simplistic ones - being blown up by TNT. TNT shouldn't make wool room travelers so OP. In the wool rooms there should be gear that could support your escape, not dominate it. Same for the diamond armor, and punch bows.

**Wool room lanes and Defending**
The wool lanes are way too easy to enter, and bypass. The cobwebs are a nice feature, but you can easily block spam over it, or go to the higher level and jump over it, or just go straight through it. It won't take long, in matter of fact it'll take way too few time. Defending is also way too hard. You can't get a decent defense set up, because of:
1) too many ways through the defense
2) TNT can undo the process of a difficult defense.

**Comment by Tywnis** [comment]
I had an update sitting, pushed it just now, let's see how you find it now.

**Comment by matic0basle** [comment]
@Tywnis Change log?

**Comment by yoyopower** [comment]
The map is around average in the rotation, it will not be removed at the moment.
