### ISSUE TITLE
Remove Coastline 

### ISSUE THREAD

**Issue by Arzanex** [OvercastNetwork/Rotations#355]
This map has been around for some time now, but I don't think the map plays very well. 

Problems: 
-Monument problems: 
 1. Too many monuments for such a small map 
 2. Obsidian monuments for all 3 create long games 
 3. Monument right outside of spawn makes destroying that monument incredibly difficult 
 4. Blockspam everywhere 
-Sand prevents tunnelling 

Opinions?

**Comment by matic0basle** [comment]
1. I think the front monuments are too easy to get. Most people will defend the back one but the front ones are also not that easy to get. All three monuments work really well with the map so I don't really see the issue here.
2. Long games are really good even if its a mini map. I really like long matches and theres defences made. I don't think its an issue.
3. Even though I agree with this, the monument is usually defended and having it where it is makes it so you can break (at least one piece) it and also enforces defending. Most matches I've played have been defended probably because of the placing of the monument.
4. Reduce the amount of blocks and put supply chests somewhere else on the map not in spawn, maybe towers that are left and right of the spawn. As for the sand I agree its difficult to tunnel, you can still go under the sandstone and tunnel there. You will have issues going up. This could be worked on.

But I disagree with the removal.

**Comment by Ipskie** [comment]
It's fine. These arguments can be applied to other maps. So long as the matches aren't infinite and the ratings are good (3.80) I think it should stay

**Comment by Typys** [comment]
I disagree with its removal,
There are few maps where defending it's actually fun, Coastline is one of those.
I don't think that three monuments are a problem, the front ones are actually pretty easily rushable, they are really close to the ground and a minimal block placement grants the attacker almost full cover. For the back one, monument modes and some skybridging are usually sufficient to end the game in a reasonable amount of time. 

Regarding tunneling, it's true that it's spotted more easily but I don't think it's a real issue, digging at the very bottom grants you easy access to front monuments, the back one is a tad more difficult to reach due to a thinner layer of sandstone in front of it, but if you know the map you can work your way around it.

I think the community enjoys this map, almost every game has some cooperations going on, and its originality is a big big plus.

**Comment by Brottweiler** [comment]
I like the map and would not like it to be removed, however maybe add monument modes to the front monuments aswell.

**Comment by Timothee38** [comment]
I don't really want to see it removed, it's in my opinion one of the best minis as it actually does not get rushed.

**Comment by thestrangeboy1** [comment]
Almost at a 3.9 rating which is hard to get. A lot of the players love this map and I think if we removed it, it would upset a lot of people. Obviously sky bridging may be a major issue but it happens late game but the fights up there are really fun. There's not too many ways to remove block spam even when there's a small amount of blocks, but it happens when matches get longer over time. I think this map will stay because of it's popularity and people tend to like long matches.
