### ISSUE TITLE
Remove cos(tnt) from Primed rotation

### ISSUE THREAD

**Issue by Shaymin492** [OvercastNetwork/Rotations#357]
Title. This map has several severe issues with gameplay. I will try to be as short and consise as possible.
   First and foremost, the map rewards chaos cannons in a very dangerous way. The entire map is made out of regenerating stained clay, a block with relatively high blast-resistance. This makes a chaos cannon the easiest. fastest and cheapest way to cannon, something new players discover after a few minutes of gameplay. Then they try to apply the same tactic on other maps, with catastrofic results. Having a map that teaches players to use chaos cannons in all situations is directly harmful to the general gameplay on all other TNT maps on the network.
   Secondly, the extremely explosive dispenser might have balanced regular dispenser cannons, but seen from a wider perspective they have made gameplay worse. The ability to make a chaos cannon with two TNT-filled dispensers as cannonball has given the players access to a ridiculously owerpowered weapon able of cleaning a 25x25x25 cube of all blocks and player in a couple of seconds. The same tactic is also commonly used to blast half a lane to pieces with a couple of dispensers, making them a very overpowered weapon. I propose we remove dispensers entirely from the map, just removing the explosion mechanic would re-create the dispenser-spread killfarming problem.
   Thridly, the combat mechanics are severely flawed. The lack of a real melee weapon is one of the problems. The ability to use a sword to block arrows and blast damage is one of the few things that makes this lego pvp game what it is, if you remove this essential ability you remove much of the complexity in minecraft combat. In combination with the no knockback diamond boots it makes pvp very broken, especially since the lanes are often covered in water from blown-up cannons.
   Lastly, the fire charges makes it unneccessary to make cannons at all. You can just run around and toss one fire charge at each cannon to oblitteriate a whiskey line in twenty seconds. This makes the first issue even worse, it is simply not worth neither the effort, nor the time to make a real cannon.

**Comment by Shaymin492** [comment]
I am aware of the fact that the map has an average rating of 3.91, but think the issues are to severe to keep it it in rotation.

**Comment by jedediah** [comment]
All evidence tells us that players generally enjoy this map a lot, so removing it is out of the question. However, your detailed feedback is appreciated and we will consider it the next time we are making improvements to the map.

**Comment by dentmaged** [comment]
I kept on getting spawn killed by a chaos cannon, I could only go into the second island (next to the hill) and I was killed there.

**Comment by HIVERaven** [comment]
@jedediah The rating from the forum form was 2.78. If that isn't enough to get a map removed, what is?

**Comment by Shaymin492** [comment]
I understand that players enjoy it, but what about the way it teaches players how to play TNT maps? If a removal is out of the question, please make changes so that you actually have to make real cannons to be successful on the map.

**Comment by twizmwazin** [comment]
@Shaymin492 The Overcast Network is not a school. The priority of the server is for players to enjoy themselves and have a good time. While cos(tnt) may not teach the best cannon practices, it is certainly an enjoyable TNT-oriented map. Not that one opinion matters, but I definitely enjoy the map.

**Comment by HIVERaven** [comment]
@twizmwazin It is also one of the lowest rated maps from the forum survey. If this map actually makes the other maps less fun, then it is technically decreasing the level of enjoyment network wide. (bit of a streach but the concept remains).

**Comment by skippy369** [comment]
@HIVERaven The forum's rating doesn't matter when the network-wide rating is higher. The people who don't like it on the forums should be rating it on the servers instead.

**Comment by varis5hawk** [comment]
@skippy369 what leads you to that conclusion

@jedediah TIL "all evidence" is in-game ratings. Forum feedback is the equivalent of an anti-Bush/Chaney cirklejerk from the American Democrat political party. The forum ratings suggest the same

**Comment by skippy369** [comment]
@varis5hawk Because the network ratings are larger and have more varying opinions than the forum's poll will. In addition to that, network ratings are ongoing while the forum's poll has ended.

**Comment by jedediah** [comment]
We care a lot more about ratings we collect in-game, because they are a much larger and less biased sample. The forum survey only confirms to me that the forum community is completely out of touch with the feelings of real players.

**Comment by twizmwazin** [comment]
@HIVERaven The in-game collected rating weighs a lot more heavily that a survey on the forums. The in-game survey shows opinions from those who accually play the map, not just those who sit there acting all smug while they insult Overcast repeatedly and wonder why they won't change to be exactly what you want.
How long people have been playing has very little to do with how the map is percievied if the map is more appealing to new players, who a significant amount of the popultaion is, it will recieve good ratings. What we should be doing is going and removing lesser rated maps, such as Iris, Race for Victory, and Fortress Battles.

**Comment by HIVERaven** [comment]
@twizmwazin if you wanted to find out what a kid's favorite teacher was, you wouldn't get the besst response on day 1, but on day 100 or the end of the year.

**Comment by HIVERaven** [comment]
@twizmwazin if you wanted to find out what a kid's favorite teacher was, you wouldn't get the besst response on day 1, but on day 100 or the end of the year.

**Comment by skippy369** [comment]
@HIVERaven Saying people who rate cos(tnt) on the servers have only played it once and rate poorly because of tg or losing doesn't make sense. First, that's a very ignorant argument generalizing non-forum users as idiots who rate maps based on tg and losing (though tg is still a valid reason to rate a map as bad tbh). It doesn't add up with the actual map rating either. You're saying they rate maps as bad if they contain tg (which all maps do) and they lose on it (which everyone loses on every map), yet cos(tnt) has a solid almost 4 star rating.

It's obviously well received on the servers. If you don't like it, stop being a jerk and keep trying to take it away from those who do enjoy it.

**Comment by twizmwazin** [comment]
@HIVERaven @skippy369 To further skippy's point, if players rated a map poorly because of losing, cos(tnt) would have a statistically low rating because 2/3 of players will lose rather than 1/2. 

Also, it doesn't matter whether the player is experianced or not. If the goal of OCN is to captivate players and keep them around, maps that are friendly to new, less experianced players are compulsory. If you wanted to look at in terms of money, these people are the ones they want to spend their money, not you who have been here, not you who have already spent your money. 

Additionally, if you want to argue that experianced players find cos(tnt) to be a bad map and find the Nostalgia maps to be good maps, I have been here for 11 months longer than you and have nearly 1.5 times the playing time. Being more experianced by metrics, I think that cos(tnt) is an excellent map that I enjoy playing.

**Comment by HIVERaven** [comment]
@twizmwazin that statistic is irrelevant, since we're talkin primed rot specific I gaurentee I've spent more time on cos and the rest of primed than you.

**Comment by skippy369** [comment]
@HIVERaven Congratulations! Now how does that have to do with you just not playing maps you don't like? The rotation isn't tailored to your liking.

**Comment by twizmwazin** [comment]
@HIVERaven I think I have passed the minimum time required to make a fair judgement. By that, my positive review and your negetive review negate each other.

**Comment by HIVERaven** [comment]
@twizmwazin That's not how reviews work.

@skippy369 Plase be less sarcastic, I don't want to get into a huge fight here.I don't expect the rotation tailored to my liking. But when I see poor gameplay on other primed maps, and I can udentify the source, ehy shouldn't I state it with shay? It's not like I'm just coming in here and making wild claims that cos is never fun, is the worst map on the netwrok, etc. I'm seeing a problem that cos causes, and stating a solution to fix it.


This post is remove cos from *Primed*, not remove it from the network. I feel it would fit better on aplha or beta, and would make the rest of the primed maps play better with it moved to a different server.

**Comment by twizmwazin** [comment]
@HIVERaven cos(tnt) is a Primed map. If you don't like it, don't play it. There is no problem sourced from cos(tnt) being in the Primed rotation. 

Additionally, reviews neither consider directly experianced or new players, but rather in combination, reletive to when the players play the map. This is directly reflected in the map ratings found on oc.tc/maps, as that shows what the players who accually play the map feel about the map.

**Comment by HIVERaven** [comment]
@twizmwazin From the op "The entire map is made out of regenerating stained clay, a block with relatively high blast-resistance. This makes a chaos cannon the easiest. fastest and cheapest way to cannon, something new players discover after a few minutes of gameplay. Then they try to apply the same tactic on other maps, with catastrofic results. Having a map that teaches players to use chaos cannons in all situations is directly harmful to the general gameplay on all other TNT maps on the network."

**Comment by skippy369** [comment]
@HIVERaven Chaos cannons are nothing new or complex, and cos(tnt) is not the central point of where people are learning to use these strats. They're used on every map, removing cos(tnt) won't "get rid of" chaos cannons on other maps that you may think get ruined because of chaos cannons. To be honest chaos cannons are the most riskiest to build because they're so easily counterable.

**Comment by CoWinkKeyDinkInc** [comment]
@skippy369 The thing is these players will not stop doing so after failing multiple times.  There are even times when they successfully fire a chaos cannon that it does nothing effective, but they will still do so.  I see countless players continue firing a cannon the same way, despite killing no players at all, destroying a target, or constant overshooting/undershooting a target, or the timing not even done properly.

**Comment by skippy369** [comment]
@CoWinkKeyDinkInc Back in 2012 this server wasn't about maps that required 'perfect strategies' to be fun in the eyes of players. It doesn't matter if the common player can't preform a standard strategy on every map - if a player enjoys making chaos cannons on a map who are you to try to limit them?

**Comment by HIVERaven** [comment]
@skippy369 75% of chaps cannons made by teammates hit teammates' cannons, even if they don't get countered. Since cos has been added, the amount of ground chaoses I have seen on other maps has gone up considerably, maybe tripled.These ground chaoses are the most likely to hit teammates cannons when they fire, even if not countered. 

Telling us that our observations that cos is causing these chaos increase is ridiculous.

**Comment by CoWinkKeyDinkInc** [comment]
@skippy369 >Back in 2012 this server wasn't about maps that required 'perfect strategies' to be fun in the eyes of players.

That's because back then, maps didn't have the same spawn kit along with repetitive, almost exact game-play as the match before.  It was fun because many different situations could happen, and you got to be ready for them.  There could have been a rush, a massive team push, cannons, etc.  Different tactics worked on some maps (sky bridging), the same tactics work horribly on others (sky bridging on BoL).  Nowadays a map that would be considered good by the forum community is a map that requires actual thinking, and doing those plans faster than the enemy.

Chaos cannons were good when players actually bothered to build a platform far away from the destructible platform/ship oh yes, and they actually worked when fired.  I got countered when building a chaos cannon on SSB long ago, killed 6 teammates and a bit of the ship, and barely build huge chaos cannons since.  You wouldn't find something like this anymore, just a person who constantly does it after failing times and times again and learns nothing in the end.  Much like how people still didn't learn that snowballs don't do anything at killing a player.

**Comment by skippy369** [comment]
@HIVERaven Where'd you get those percentages? Removing cos won't remove the supposed "chaos cannon increase" either, which I still don't think has much to do with cos(tnt), chaos cannoning has always been a popular tactic.

@CoWinkKeyDinkInc What? Maps back in the day were literally copy pasted chests from other maps. The games weren't boring because there weren't developed strategies that you needed to follow or else you or the map you were playing was branded as bad.

If people fail time and time again at making a chaos cannon, you can only try to help them by telling them a better way to build it (without being an ass, too) or leave the current map. That stuff happens on all TNT maps.

**Comment by twizmwazin** [comment]
@CoWinkKeyDinkInc 

"That's because back then, maps didn't have the same spawn kit along with repetitive, almost exact game-play as the match before."

Most games I play in on older Nostaliga maps are pretty much all the same. One team quickly goes and blows up the other team's side completely, and then you just sit there and watch as they kill farm and eventually bother to get the objective after they feel they have gotten sufficent kills. There is no such thing as a "comeback" in these games, because they have no supplies to do it with. The closest thing to a comeback is when five guys go and punch a full diamond guy out of the world, after he killed only four of them. On the other hand maps like cos(tnt) or Ender Blast go back and forth, never is any team completly out of luck until the game is accually over.

**Comment by CoWinkKeyDinkInc** [comment]
@twizmwazin That is because of donor stacking and team stacking.  There can be comebacks on Nostalgia maps, especially on SSB.  I have observed many matches where one ship was torn apart but they eventually win.  I can easily find all materials except diamond armour in two minutes or less when much of the chests are gone.

**Comment by HIVERaven** [comment]
@skippy369 Chaos cannons were always used, but never as frequently, or as carelessly since cos. Now I see more and more of them on the ground of other maps, because this is a often used tactic on cos. Please stop telling me that I am wrong in observing this.

**Comment by skippy369** [comment]
@HIVERaven I'm not telling you you're wrong, I'm more saying this has always been happening. Even if cos(tnt) is somehow the reason behind the apparent increase of chaos cannons, removing it won't fix the "problem".

Anyways it's been said that the map won't be removed above. So I'm done arguing.

**Comment by twizmwazin** [comment]
@CoWinkKeyDinkInc On SSB, usually diamond swords, bows, arrows and maybe TNT can be found easily. However, supplies to build a cannon or do anything tactical are gone. At that point, it is just mindless TNT running. Chaos cannons, or maybe a very basic whisky, are the only possible cannons. At that point the map fits why people feel cos(tnt) is bad, because many cannons are not practical, chaos cannons are good, and mindless TNT running. The only difference it that cos(tnt), with its spawn kit, opens up the possiblity to escape this.

On team/donor stacking, it is ineffective in cos(tnt) the map can't be completely dominated the same way that they can be on Nostalgia maps. A team can control an island, but a strong push can capture a point. And just because a team is losing 5 minutes into the game doesn't guarentee a victory the same way it would on most Nostalgia maps.

**Comment by varis5hawk** [comment]
@skippy369 how would it not make the situation better wat

**Comment by skippy369** [comment]
@varis5hawk Removing a map will not remove the idea of chaos cannons. They are one of the most simplest and most common cannons on oc.tc.

**Comment by HIVERaven** [comment]
@skippy369 How many times do we have to tell you that we're not trying to remove chaos cannons, but remove the tendency of people to put them on the ground every single time?

**Comment by Shaymin492** [comment]
@twizmwazin @jedediah  "The Overcast Network is not a school. The priority of the server is for players to enjoy themselves and have a good time. While cos(tnt) may not teach the best cannon practices, it is certainly an enjoyable TNT-oriented map. Not that one opinion matters, but I definitely enjoy the map."

False. The Overcast Network is a school whether you like it or not. New players are going to look at more experienced players to learn basic strategies. When the experienced players are just chaos cannoning and TNT running we have a problem. If the easiest way to get kills on cos(tnt) is TNT running and chaos cannoning the player will try this strategy on other maps. This is what has caused the increased useage of chaos cannons. I understand that the map is fun, but so was Hydrolock. Hydrolock damaged the network as a whole due to easy wool farming. cos(tnt) is its equivalent in many ways, it damages the network gameplay-wise. Also, @jedediah , I do not agree with the way you interpret the data you get out of the rating system. Expect a forum thread within the next couple of days.

**Comment by twizmwazin** [comment]
@Shaymin492 While a school is a place of learning, not all places of learning are schools. At a grocery store, you might observe somthing and learn somthing, perhaps in an advertisement. That does not make it a school however.

**Comment by HIVERaven** [comment]
@twizmwazin Does it really matter whether we classify it as a "Place of learning" or a "school"? Either way, Shay's point that it damages the entire network much like hydrolock is correct.

War Wars is arguably the most fun map in the repo. Please put it in all the servers. Thank you. /s

**Comment by twizmwazin** [comment]
@HIVERaven It doesn't damage the network in any way shape or form. You cannot blame player's poor strategies or decisions on maps you like by blaming maps you don't enjoy to play as much.

**Comment by Shaymin492** [comment]
@twizmwazin Yes you can. Did you even read my post?

**Comment by twizmwazin** [comment]
@Shaymin492 Yes, and I think you are assuming too much

**Comment by HIVERaven** [comment]
@twizmwazin You're entitled to that opinion, but with all due respect I think that we know what we've seen and we can confidently attribute it to cos.

**Comment by Shaymin492** [comment]
@twizmwazin That there is a corretion between the increased use of reckless chaos cannons and the addition of cos(tnt) is a fact. The question is if it is a causality of not. As I do not know any other thing that might have caused this sudden increase, it is only logical to draw the conclusion that it is also a causality. I hope this made you understand how I am thinking.

**Comment by twizmwazin** [comment]
@Shaymin492 I understand how you are thinking, but I think you are looking too deeply into the situation. I think the issue with chaos cannons is that many players do not know any better, as they are very easy to construct, even compared to a basic whiskey. However, this does not in any way coorilate with the map cos(tnt). cos(tnt) is a map that has been able to cope to this strategy, as it is a new map which follows the meta rather than leads it.

**Comment by Shaymin492** [comment]
@twizmwazin I think it took the beginning of a meta and developed it into full bloom. Let's leave it at this, it doesn't really matter since no action will be taken.

**Comment by HIVERaven** [comment]
I think we need to revisit this, especially with the results from the forum feedback survey.

**Comment by twizmwazin** [comment]
@HIVERaven Seeing how you are banned for the next two months, I don't think it is appropriate for you to make any comments. I don't see why you want to remove the third most liked map from Overcast. In fact, its rating has gone up since this was last visited.

**Comment by HIVERaven** [comment]
@twizmwazin Seeing how we aren't supposed to discuss punishments here, that's irrelevant. From the forum feedback survey it had a rating of 2.83 (Worst of any map from the survey other than KI, which is removed already). In addition, 30% of those surveyed on the forums rated it 1, which was the highest of ANY primed map except KI (Removed already).

**Comment by twizmwazin** [comment]
@HIVERaven Link?

**Comment by HIVERaven** [comment]
@twizmwazin I do not have permission to distribute it yet, but I can assure you that those stats are accurate.

**Comment by twizmwazin** [comment]
@HIVERaven Quoted from the FAQ "There are tens of thousands of players on Overcast. The vast majority of them do not post on the forums or express their opinions in any public way. Are you sure you know what they want?"

**Comment by CaptainElliott** [comment]
A lot of people like the map. Can't you just sit out one match while it plays

**Comment by HIVERaven** [comment]
@CaptainElliott According to the feedback form from the forum, 30% of players who responded rated it 1. That's an incredibly high amount. In addition, it usually takes 22 or so minutes, due to it being impossible to rush or even end quickly. I've never seen a match on it last less than 15 minutes. Lastly, if you look through the past comments here, especially the ones by me and shaymin, the map teaches other users bad habits and changes the way other maps are played for the worse.

**Comment by HIVERaven** [comment]
@twizmwazin There may be 10's of thousands over all time, but currently it seems more like around 500 at a time. In addition, those "tens of thousands of players" give a tiny rating, whereas the regulars, especially the ones you see here responding, are putting in paragraph and paragraph as to WHY the map should be removed, WHAT it does wrong, and the reasoning for everything. Surely the 50 paragraphs I've put in over the last 6 months to why I think this map should be removed is more important and valuable than the /rate of a random player who joined and rated the map great because they didn't understand the match but they liked watching the exploding blocks go WHEEEEEEEEE over their heads, and because they haven't experienced the endless repetition of the map that never plays differently from time to time again.

**Comment by twizmwazin** [comment]
@HIVERaven All of your whining and complaining do not amount to anything. As one player, your /rate 1 is your equal voice. I for one, love cos(tnt). I do not see any major faults to the map. I am going to suck up with last_username and fully agree with his statement from the FAQ. As you have seen, making this argument again and again will not get you anywhere, as the administrators and map developers have made their decision.

**Comment by HIVERaven** [comment]
@twizmwazin So you are fine with ignoring the fact that 30% of regulars HATE the map, and that they rated it the worst map currently in rot?

**Comment by twizmwazin** [comment]
@HIVERaven Seeing how 50% of players who have ACTUALLY PLAYED the map rated it 5, your argument has no support. A minority of like-minded people is not a representation in any way of a majority.

**Comment by HIVERaven** [comment]
"Seeing how 50% of players who have ACTUALLY PLAYED the map rated it 5, your argument has no support."

LOL

**Comment by twizmwazin** [comment]
@HIVERaven I'm happy to see you find me humorous, however I [do not make up numbers] (https://oc.tc/maps/cos_tnt_).

**Comment by HIVERaven** [comment]
@twizmwazin I was gonna pull an arch and just ruthlessly destroy all your refutals of my points, but you *Don't HAVE any*. Calling my data made up is just ignorant and just plain ridiculous. When I'm allowed to link it to you, I will.

**Comment by twizmwazin** [comment]
@HIVERaven I'm not sure what your good arguments are. For what I can tell, they seem to be:

- I don't like this map
- I don't care that other people do, because I don't know them and therefore their opinion does not matter.
- Someone else decided the the Institution of Overcast has poor teachings.
- I can talk about dated statistics that no one has access to to try to prove my point.

It is because of your weak and clearly ineffective arguments that I cannot make a solid counter-argument.

**Comment by mrapple** [comment]
From the FAQ "There are tens of thousands of players on Overcast. The vast majority of them do not post on the forums or express their opinions in any public way. Are you sure you know what they want?"
