### ISSUE TITLE
Add SolitudeMC to more servers

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Rotations#359]
This might sound a bit biased wanting it on more servers but it doesn't get that much play time with the current server dynamics and EU Mini03 and 04 being open only in the later evening but the map is one of the best rated DTC maps ATM and it should appear on rotations a bit more. The server dynamics are not to be blamed here though as they are being worked on.

I think it would be nice to see it on two more servers mentioned bellow so it would get some more play time as it is one of the best DTC maps looking at the ratings. I've been looking for matches that play the map just to see what players think about it and seeing ratings after matches.

The ratings have also improved in the past couple days from what I've seen. At some point it was at 3.72 but its rising back up and is currently sitting with 3.75 which currently puts it at the 3rd highest rated DTC map and the best highest rated Mini DTC map. The only two maps above it are Blocks DTC and Avalon Funland

![](http://i.imgur.com/hQdLbxG.png)

![](http://i.imgur.com/QEowQWr.jpg)

Posible servers: Mini01 US and Mini01 EU

**Comment by TheGunningAlien** [comment]
+1 One of my favourite DTC maps.

**Comment by HIVERaven** [comment]
+1 A very fun mini-DTC

**Comment by DoomRobotBoy** [comment]
It is a fun map to play from time to time. But it's kinda stale. 

- You aren't given a lot of options with defending, making that usually boring after doing it a couple of times.
- The map usually results in sky-bridging, which is - even though sky-bridges are pretty easily destroyed because of stone and stained clay are both quickly destroyable with a diamond pick - still a problem. Destroying it may be easy, but when an entire team storms in (like with most sky-bridge heavy maps) it'll usually result in a win for the sky-bridging team.

However, I wouldn't find it a problem to let it get added to more servers. I also have a map in Mini03 EU (though it's also on US) and it's indeed never on. Not quite sure about Mini01, since that rotation already contains a lot of DTM maps (and 1 DTC map). I'm sure it can fit somewhere though.

**Comment by Ipskie** [comment]
Isn't this more a problem with dynamic servers than the rots? I would prefer this: when the overlord decides to start up (even after a restart) a mini server, it chooses a random one. This would randomise rotations and make things a lot more fun

**Comment by matic0basle** [comment]
@DoomRobotBoy Defending will be worked on in a future update  About the skybridges I am thinking of something that I could do but it would be probably hated by most players. Though theres been a lot of improvements on that with lowering the limit and adding the clouds-

**Comment by Arzanex** [comment]
Personally I think the map is a little stale, maybe widen the map so that there are more options to get into their side.

**Comment by matic0basle** [comment]
@Arzanex I think that would ruin the map to some point. It would be useless space that noone would go to. If anything it would be rushed and from matches ive seen it goes fot 10 to 15 minutes on average which i think is a good lenght for a map its size

**Comment by Mikeg542** [comment]
I really like this one and think it generally plays really well. I would agree.

**Comment by ParaSpider** [comment]
I wouldn't be opposed to this change. Would rather like it actually. 

Support.

**Comment by Buo111** [comment]
This is one of my favorite maps and it's fun and playable. I'm agreed with this.

**Comment by Ipskie** [comment]
Which servers and where in their rots?

**Comment by matic0basle** [comment]
@Ipskie I suggested Mini01 in the OP on US and EU but it can be on others too. And where it fits the most by the player amount.

**Comment by matic0basle** [comment]
Could I get an update on this? It is now the highest rated DTC map overall with the rating of 3.85.

![](http://i.gyazo.com/ec34dab17cea2012d3849c3890d5065e.png)

**Comment by DatCoomboo** [comment]
The best Mini DTC of the world..

**Comment by SheriffSoco** [comment]
Please bring this higher up the Mini rot list
