### ISSUE TITLE
Remove PixelMix

### ISSUE THREAD

**Issue by matic0basle** [OvercastNetwork/Rotations#372]
This map was recently added to Capture rotations with the rotations update. Even with the decent ratings there are still a lot of issues with the map which is why I would like to see it removed.

 - Blocks
   - The amount of blocks in the spawn kit is too big. The maps size and 3 stacks of blocks don't get well together, The blocks need to be cut down because ATM its just block spam to the wool and you are done.

![](http://i.imgur.com/A48QS5W.png)

![](http://i.imgur.com/7dEId6h.png)

   - Block spam, Die, Repeat
     - Pretty much this is the only thing people do. I played the map and in the matches I played people continued doing only this. They spawn, they block spam and attempt to get the wool, get shot or meleed to death, repeat. Eventualy someone will get in.

 - Defence
   - Since you can't destroy the mushrooms theres not really a good way of defending. Yes you could make a defence on the grassy area but doing it alone won't change anything. Enemies will get in with block spamming before you make a defence. 
     - Possible fix to this issue would be redoing the lanes to the wool rooms. Remove mushrooms (maybe leave the last one) and turn the rest of the area in normal grassy land.

 - Rushing
   - From the matches I played, all of them ended really quickly. Why? Because of the block spam and the "block spam, die, repeat" tactic I mentioned above. Theres no way to really defend due to the lanes so matches are just very short.
       - I went through the matches page and went to look for past matches of PixelMix. Was not really surprised that most matches ended faster than 5 minutes. The gist paste below will give you match links to the matches.
https://gist.github.com/matic0basle/517f5a3fdda3d0771397

So please consider these notes when updating the map Authors and Map Developers please consider removing the map. It just doesn't play that well.

**Comment by ItsMiiOlly** [comment]
The author has plans to update the map.

**Comment by matic0basle** [comment]
@ItsMiiOlly Until its updated, my opinion still stands. Would be great if you could link him this issue so he could possibly think about the issues I mentioned above and solve them.

**Comment by DoomRobotBoy** [comment]
Ye I know about he issues. To be honest I was quite surprised it was added before I fixed those, but oh well... You can expect an update fixing all these issues soon.

**Comment by matic0basle** [comment]
@DoomRobotBoy Awesome!

**Comment by ItsMiiOlly** [comment]
I've reduced the amount of blocks.

**Comment by DoomRobotBoy** [comment]
@ItsMiiOlly oh, while you're at it could you possibly (if not already done) lower the maxbuildheight a bit. I have been getting some complaints which are true based on my observations. The maxbuildheight reaches about 30 blocks above the normal surface, so you could possibly lower that with ±8 blocks?

Though, since I am updating it anyway I could also do it myself.

**Comment by HIVERaven** [comment]
Pretty cool map, although the feather for increased speed seems kind of gimmicky, maybe a 10 second splash pot would be better

**Comment by brettodgen** [comment]
test

On Tue, Jan 27, 2015 at 12:10 AM, HIVERaven <notifications@github.com>
wrote:

> Pretty cool map, although the feather for increased speed seems kind of
> gimmicky, maybe a 10 second splash pot would be better
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OvercastNetwork/Rotations/issues/372#issuecomment-71590752>
> .
>



-- 
Regards,

Overcast Network Tournament Support
refs@oc.tc
https://oc.tc

**Comment by EyQu** [comment]
Would you also consider adding some bedrock in the mushrooms and having the ability to break them?

**Comment by DoomRobotBoy** [comment]
@EyQu Tbh the times I played the map it was very possible to defend it. Of course I knew the map better than new guys, but still there is a possibility.
Also, since the wool room lane is going to be changed I don't think those mushrooms need bedrock.

@HIVERaven I have no plans on changing that, sorry. The feature of a speed item once holding it really adds something cool to the gameplay. If you want to have speed you can't hurt others. Its like making a sacrifice. I am thinking of boosting the speed amount a bit up so more people will use it.

Also in general, the map was added to the rotations without my knowing, while I was completely aware of its problems. Pointing them all out over and over won't really help. IMO the map could even be taken out of the rrotation, just to spare repetitive suggestions and low ratings. I'll be able to update the map tomorrow, and most likely not sooner.

**Comment by DoomRobotBoy** [comment]
I hope that did not sound douchy :(

**Comment by Ipskie** [comment]
@DoomRobotBoy if you do consider the map to be really bad in it's current state, you can ask for it to be removed from rots until a better version is made. Worked for Ender Blast

**Comment by DoomRobotBoy** [comment]
@Ipskie Even though that would work best,  I can release an update tomorrow and bugging the MapDevs for that over today and tomorrow I feel like that would cost more effort than actually needed.

**Comment by ItsMiiOlly** [comment]
I've taken it out for now while we wait for the update.

**Comment by DoomRobotBoy** [comment]
@ItsMiiOlly Here is the updated version (v1.3):

https://github.com/OvercastNetwork/Issues/issues/1566

**Comment by DoomRobotBoy** [comment]
Can this be added to rotations again? According to the revisions page the map is updated. If it is still not living up to expectations we could open the discussion again.

What do you think about adding it back to rotations, @ItsMiiOlly?

**Comment by ItsMiiOlly** [comment]
Re-added to rotations. I've also reduced team sizes to 25v25.

**Comment by TiTo-418** [comment]
+1

**Comment by Superjd10** [comment]
@TiTo-418 Why +1ing a closed issue?

**Comment by TiTo-418** [comment]
Porque no podes reabrirla ni crear una nueva, como actualmente esta en las rotaciones, prefiero que lo saquen
