### ISSUE TITLE
Remove Khaba

### ISSUE THREAD

**Issue by TNTTurtles** [OvercastNetwork/Rotations#374]
Yes, I am aware this is one of the most highest rated maps, but in all honesty of my opinion it plays terribly.
Gameplay is just tedious. Here is how I describe the map, just hold down right click with grenades in your hand until you kill somebody.
The aesthetics is just 2 buildings copy and pasted with world edit.
The map is also extremely repetitive and it gets very boring within 2-5 minutes.
Please remove this.

**Comment by TNTTurtles** [comment]
NCP also tends to get pissed off easily on this map.

**Comment by Majjus** [comment]
You don't just hold down right click if you don't want to waste grenades. There's also double jump, power 2 bows and special super grenades and TNT which are unlocked when you've killed X amount of players.

There are several different building and due to gravity they'll collapse which makes map landscape different every match.

It is one of the highest rated maps (4.02) and is imo very fun.

**Comment by DoomRobotBoy** [comment]
@Majjus Even though his wording maybe a bit exaggerated, it is kind of true. Grenades dominate this map, and as a bonus are also capable of blowing up buildings. 

The map looks fun at the start, and still does a few matches in, but with grenades flying everywhere, killfarming the guys without grenades and blowing the map to oblivion it gets annoying rather quickly. Ratings are maybe high, because the map is chaotic and innovative (because of collapsing buildings), but we had more of these chaotic type of maps and I don't think we should be promoting them more.

**Comment by Ipskie** [comment]
I'm not a fan of the map,  the grenades play far too large a part in gameplay

**Comment by Tapetepato** [comment]
Agree! https://github.com/OvercastNetwork/Rotations

**Comment by thestrangeboy1** [comment]
> Here is how I describe the map, just hold down right click with grenades in your hand until you kill somebody.

Yeah, good luck with using all your grenades. If you're not conservative with them you're forced to use your bow or sword which isn't as useful as the grenades. 

> The aesthetics is just 2 buildings copy and pasted with world edit.

The buildings get demolished anyway so what did you want, some variety in the clusterfuck of blocks falling on the ground with the falling block module?

> The map is also extremely repetitive and it gets very boring within 2-5 minutes.

If you find this map being repetitive, then I'd love to hear your opinion on the other 100 TDM maps we have. The fact that the grenades actually shape the map with the buildings falling down with no support makes it interesting instead of the same layout of buildings. Sometimes you can have the middle building teared down and it's an open field in middle which allows for more people to use their bow. 

The map is in what, Mini02 and 6? You're not going to play it often and some people enjoy it, especially with a high rating of 3.89.
