### ISSUE TITLE
Add new server for newer maps, change Primed

### ISSUE THREAD

**Issue by Z3R0Z3R0Z3R0** [OvercastNetwork/Rotations#375]
Over the past 6 months I've seen a huge gap in a few things. The regulars want Tournament Style TNT maps, like SSB and Fractal Descent. The newer players, and some of the innovative map makers are going to different style of gameplay, and unfortunately the two don't mesh well. On Primed, we have a combination of the two. The newer maps are the ones with full spawn kits, without supply chests, with heavy XML gameplay. I've come to see that a good amount of people like those maps. And theres no denying that, those maps get good ratings on the servers. But, as shown in the feedback on the forums and the surveys taken there, the regulars, and I'm sure some non regulars, enjoy the older forms of Primed.

Heres the suggestion: Change primed, but add a new server. One for tournament style TNT DTC/M maps, and one for innovative and newer maps. It could be called Innovation, or maybe just something simple like Gamma.

Sample Primed Rotation would be:

Woodwork Harbor
Fractal
Iris DTC
Fortress Battles
Interitus
Retal 2
SSB
BVIII
Totally War 2
Adaptations of the maps made for potential Tourney 9 maps, but changed to suit public play.

Sample Innovation/Gamma/whatever the name would be Rotation:

BoomBox
Cos(TNT)
DATAbasin
DATAstation
EnderBlast
Zap
Kï
Greed
DK crossovers
There are more of these maps being made all the time (Surrounded by Coolstorybrofish )
This rot could also be supplemented by maps that don't have TNT, but are innovative, such as Battle Ecliptica III, Khaba, Sandbox, Sequential and those type maps.

This would solve the issues on Primed of the Regulars who want to play on maps that are tourney style, and would give the players who like the new breed of innovative maps a new place to play them all.

**Comment by nygiants10** [comment]
I agree with this. I much prefer the newer style of maps, and would like to see this tried out. With Primed having as big of a server population as it has, I think it could support, and would benefit from, this sort of split. This would also end a lot of the disagreements and drama I've seen on the forums about the growing number of "experimental," modern Primed maps on OCN taking over the "tourney gameplay" server.

**Comment by Ipskie** [comment]
This would be pretty sweet, though I am concerned that there would be backlash from people who don't like TNT in general.

I do think that splitting the 2 rots is correct, given that the gameplay and aesthetics of both are so radically different

**Comment by Z3R0Z3R0Z3R0** [comment]
@Ipskie An important thing to do would be to make Innovation not just about TNT, but about innovation in general. Sandbox, Greed, and Khaba are all non-TNT focused maps that are innovative and would show how Innovation isnt just tnt maps

**Comment by CoWinkKeyDinkInc** [comment]
I wouldn't prefer calling it Innovation, but I do like the idea of a server.  The name implies that only innovative maps would be found on that server, and the some that just joined may consider that better just because they haven't been around to know how it innovates from other maps.  It'd be a nice addition to replace the two or so Mini servers that never seem to be open as this server can fit more players.

**Comment by Z3R0Z3R0Z3R0** [comment]
This would essentially solve #374 #300 #357 #266 #261, and many others.

**Comment by Z3R0Z3R0Z3R0** [comment]
In addition, another option in this would be to remove Nostalgia. A good portion of the nostalgia maps would fit on the changed Primed (Airship Battles, SSB, Avalanche, Fortress Battles), and the rest would be put in separate rots as suggested in the Remove Nostalgia idea, and would put a server up for the new people who really enjoy the newer breed of maps.

**Comment by CoWinkKeyDinkInc** [comment]
Just so you know, you can edit your comments by using the pencil in the top right.

**Comment by Z3R0Z3R0Z3R0** [comment]
@CoWinkKeyDinkInc Yes, I did know that, I was also going for the subtle bump. I commented teice because I had 2 seperate thoughts to add.

Just so you know, you can tag me and give me a notification by using the @username function /s :-)

**Comment by Z3R0Z3R0Z3R0** [comment]
Can we please have some mapped feedback on this?

**Comment by ItzaMeLuigi** [comment]
Sounds like a good idea to me.

**Comment by Shaymin492** [comment]
+1
This would make all players happy, both the cos-lovers and the people wanting tournament-styled maps.

**Comment by SuicuneScale** [comment]
Heavily in favour of this. It satisfies everyone, and I don't see any downside to it.

**Comment by Superjd10** [comment]
Completly agree, everyone would be happy.

**Comment by thestrangeboy1** [comment]
Adding another server at this point is useless unless removing nostalgia will be a thing. With the most recent dynamic server change we don't even get past mini04 for servers to turn on most of the time. With the amount of maps with TNT as it stands, we barely have enough for a decent rotation. Fortress, Interitus, Retaliation 2, and SSB are maps I think don't work well anymore because their objectives are really easy to get now and 3/4 of those maps have supply chests with normal players don't really like a lot (see nostalgia ratings as almost every map in its rot has supply chests). We'd barely have a rotation with the remaining maps and unless more TNT maps can be produced, I don't see a point in another server.

**Comment by Z3R0Z3R0Z3R0** [comment]
@thestrangeboy1

I disagree about those maps playing poorly, I believe they would play well if and only if they had a rotation dedicated to maps similar. They get rushed because some players want the xml heavy cos, which consequently can't be rushed by those who don't like it. If the rotation was completely composed of tnt tourney style maps, they would play better.

I don't think there would really be a problem with removing nostalgia if there was a good alternative to it, which there currently is none (This idea would solve that.) When apple me tioned removing nostalgia, he was met with a ton of resistance because the nost regs really didn't want to be forced to play on xmlprimed.

**Comment by Ipskie** [comment]
@Z3R0Z3R0Z3R0 I don't think that a rotation really affects the maps around it. I also don't think that the reason maps get rushed is _because_ people are trying to get to cos, it's just because they like rushing and cos can't be rushed. If people really liked XML heavy then BoomBox wouldn't get rushed, which does happen

**Comment by Z3R0Z3R0Z3R0** [comment]
@Ipskie Point taken, but the rotation absolutely does effect the maps around it.

Overcast has grown, and was built on competition.The earliest days were competitive, even if they weren't organized tourneys like recently. This server would probably end up being a bit more competitive than the others (Think OG primed. Lots of experienced players who are able to counter rush) and this would likely improve gameplay. OCN was built on competition, has grown on it, and should have at least 1 server that reflects it.

**Comment by Electroid** [comment]
Primed is getting a change, you'll see a post soon.
