### ISSUE TITLE
Prioritize Deathmatch in Dynamic Servers

### ISSUE THREAD

**Issue by nygiants10** [OvercastNetwork/Rotations#377]
Deathmatch should be up the majority of the time, if not all the time on Overcast. It is one of the most popular servers for regulars to play on, as the plethora of forum threads made on this topic recently have shown. TDM is a keystone of this server, in that it is one of the first things many new players come here for, and the big team fights are what many of us think of as the basis for Overcast Network gameplay. We should have, at the very least, one of each of the major gamemodes available to play at all times, and TDM really should be added to this list of "high-priority" gamemodes.

**Comment by Z3R0Z3R0Z3R0** [comment]
In addition, TDM is by far the easiest for new players to learn, not needing a tutorial at all

**Comment by matic0basle** [comment]
I think its better if we keep it all in one place. Post it here:
https://github.com/OvercastNetwork/Issues/issues/1368

**Comment by Z3R0Z3R0Z3R0** [comment]
@matic0basle isn't it far batter to address each specific part of the issues, and each specific change instead of all at once, so that we actually get things done? Changing 1 server's order wouldn't take much effort, and based on the support we've seen for it, a single issue for that change is the best way to get the change.

In addition, that issue of yours is over 2 months old, hasn't been updated in 2 months, and deals with quite a few things that are unrelated to moving deathmatch's spot.

**Comment by matic0basle** [comment]
@Z3R0Z3R0Z3R0 They are planning on redoing the whole order (i assume from the responce on my issue) so it doesn't matter if they switch one now, its better to fix the issue completely in one go.

And it doesn't matter when the issue was last updated. Its still open and apple commented saying its WIP so theres no point having multiple issues if they already have it on their to-do list.

**Comment by mrapple** [comment]
This is for rotations issues only
