### ISSUE TITLE
Remove Snowy Wars: CTF

### ISSUE THREAD

**Issue by ParaSpider** [OvercastNetwork/Rotations#381]
It's too stalematey. There's a point where there's a fun stalematey, and a boring, annoying stalematey.

Snowy Wars CTF is too difficult as if the DTM wasn't hard enough; in the DTM you actually were there once you were there. Now, you have to run back and forth which makes it even worse. It takes exactly 7 seconds to run from your spawn back to the flag in defense terms, and it takes 36 seconds to get to the flag, not counting going back for the enemy. In total, it takes 7 seconds to defend yet 72 seconds to get the flag when you do come back.

With just 3 defenders as with the match I'm in, it's near impossible to get to it. The void near the flag is the most annoying part, especially when there's tons of random melted water and blockspam to navigate through, making it easier for you to just die. It's hard to make any actual defenses anyway, because we're limited to just 16 planks. You can't really get the flag even with that, and the planks don't drop. It's too difficult, and it's not really a challenge.

The map itself is poorly designed in my opinion anyway, and with 16 planks it's difficult to make bridges to move forward, so no skybridges or just even long, or underbridges. It's run, die, run, die. I just can't see it nor has it been seen playing well, and I would prefer that it stay out of rotations, possibly even repository.

Nothing further to say.

**Comment by Ipskie** [comment]
Is it actually in rotations? If not there isn't really an issue to be had here...

**Comment by matic0basle** [comment]
@Ipskie Its on Broken rotations which does have a file in the US folder.

**Comment by Tapetepato** [comment]
-1 It's really fun (imo it plays even better than the original one). Most of the times it doesn't last that much but it do last 10+ minutes and that is a good time for a match, also, its a break from all those rage fast paced maps. The 16 planks thing is great, since on the original map was too much blocksmap, and since here the objective is easier to get than on the other one i think its fair enough to have less blocks, this way you don't waste them on a reckless way and you can work with your teammates to advance on your bridge, defense etc. You can also mine the blocks from the bridges and trees to get extra wood. 
I do think the blocks should drop tho

**Comment by Brottweiler** [comment]
It's just one flag though... I agree that it's very stalematey, so it should be improved, not removed.

**Comment by ParaSpider** [comment]
Resolved, it seems
