### ISSUE TITLE
Add Palace CTF

### ISSUE THREAD

**Issue by yoyopower** [OvercastNetwork/Rotations#385]
Broken seems to be testing a lot of the CTF maps (nearly all of them) with the current rotation and we'd (Diamyx and I) appreciate it if Palace could get added. This would give us more feedback/ratings and help us improve the map. The current average rating is 3.7 which we hope will improve with the latest update.

**Comment by Arzanex** [comment]
This was tested while I was online and I agree with the addition.

**Comment by DoomRobotBoy** [comment]
I still have few problems with it. Because the map is pretty thin (in terms of width), but pretty long, its hard to get past all the fights going on in the center. 

There are a few ways throughout the map, next to the normal walking over the surface (sewers, palace, bridges on top of palace), but those are rarely used, because they are not as obvious. When I tried running to the other side I was easily spotted, until I found the deserted runway in the palaces, and thus almost got an easy cap.

I think the reason players meet in the center is because one side of the map is very open (from flag to other flag) and the other side is just a large palace. An obvious thought would be to walk through the open part, as most guys did, but that'll just result in a clash between the teams, which won't speed up the match' endurance.

If the player flow will be more spread I'll be happy to rate it 5 (I probably already rated it 5 -.-)

**Comment by yoyopower** [comment]
@DoomRobotBoy 
 - The map is designed to have a fight in the middle for control, we don't want everyone to slip around it.
 - The map is designed for team pushes, Diamyx and I just spent around 2 hours balancing the map for this aspect, we don't want people to be easily able to solo cap the flag.
 - The sewers are obvious; there's 3 large holes in the path leading to them. The routes in the top of the buildings may not be the most obvious but should be obvious enough to try them (You can see bridges up there and there's paths leading to places you can get up from.
 - As said above, we want their to be a fight in the middle. With the new balance update we think it'll become more team orientated and therefore more tactical.
 - People follow the main paths, which is the intention of the map. Diamyx insisted on making this map though: http://i.imgur.com/wHvee2E.png (Note: He used the picture from the first version, so things have changed slightly.

(Not sure how this will look, typing from phone).

**Comment by DoomRobotBoy** [comment]
@yoyopower You say the map is designed to have a fight in the middle and not have everyone slip around.

Then why did you focus so much at making the center hard to control, BUT also have sneaky ways around it, which only experienced players know. I had less than no trouble walking through such a sneaky way. If you want to have the fight centralized than design the layout that sneaking around isn't easy.

I haven't seen anyone use the sewers, but then again I haven't used them myself as well, so I can't really say anything about it.

The paths aren't THAT obvious. There are just ladders, but ladders are not obvious.

The picture makes less sense then why Diamyx is not an IRL sewer rat, kappa.

Lastly, I wanted to add something to my 'suggestions/complaints':

- The insides of the palace seem very empty, they look pretty bad and don't really give any great fighting (small hallway = boring fighting). Just add some pistons, or something else as decorations, so gameplay is improved and it also looks better.

**Comment by yoyopower** [comment]
@DoomRobotBoy 

There is one "sneaky" way around which is the sewers. You can not go above ground and the sewers are fairly obvious (3 holes in the main path going straight to them). (This point is referring to the middle).

We can't exactly paint a flashing neon sign saying "there's a route up here". There's a path leading to the ladders and obvious bridges connecting the buildings.

Sewers may be deleted, we're not sure yet (hence why we're asking for more play testing in the form of getting it added to the testing rotation).

Agreed, I'll add this to the new update. (Insides are empty).

**Comment by DoomRobotBoy** [comment]
Palace was added in the latest rotation update, so you can close this issue.

https://oc.tc/revisions/rotations
