### ISSUE TITLE
Add Outback to Capture

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Rotations#387]
With the update to version 2.0.0 the map changed a lot, the gameplay really was improved and players do enjoy the map more and more, this can be seen when looking at the ~400 ratings. The average is 3.79 with higher tendency.

The map thread:
https://oc.tc/forums/topics/54cd1496c29635c7c400284f

**Comment by DoomRobotBoy** [comment]
I agree that the map plays good.

Defending is easily done, and when doing so you actually feel like making progress (since big pits are not difficult to create on this map), making defending an encouraged role in this map.

The layout also works great for offending. Even though you still see most players go through the center, every lane is in fact used, allowing some variety in gameplay.

**Comment by thestrangeboy1** [comment]
There's a few problems I have with the map. I think that there's way too much cover around the islands and the front lines. In most CTW maps you have these islands that are sometimes very open or have minimal cover, but these islands have 2 high walls around pretty much the whole island. Front lines are full of trees too that are awfully low which makes it hard to see in front of it from a distance and it makes most offenders just use the tops of the trees. 

The wool rooms are a pain to get out of. You can't build in them and everything is made of half slabs so you're constantly getting shot by 1 or more people. There's barely any room around the wool room as well because there's a premade pit right in front of there too.

One thing I do like is how you face the iron when spawning so people can immediately know where it is. Adding the defender chest was a great thing as well because I see lots of people using those for defending which I think is great.

**Comment by rockymine** [comment]
@thestrangeboy1: I am going to fix these points soonish. 

As for the islands and the frontline I'll remove some of the trees and the walls.

For the wool rooms I'd plan to remove the pre made pit and redesign it. Furthermore I'll see if I can add some more space around it to make room for more entrances and higher mobility.

I'd really like to thank you for this detailed feedback, it's helping me along nicely. When I've fixed the listed problems, would it be mostly ready for being taken in consideration for a rotation update?

**Comment by rockymine** [comment]
@thestrangeboy1: https://github.com/OvercastNetwork/Issues/issues/1749

**Comment by matic0basle** [comment]
@rockymine Just be patient. You only created the issue a day ago, give them some time to go through and see if the update is working.

**Comment by Oo-TheFrog** [comment]
+1 I would love to see this added if the lanes in front of the wool room became thinner they are way to tall currently its very hard to set up defense.

**Comment by rockymine** [comment]
@ItsMiiOlly: Why have you closed this? The Duplicate was removed already.
