### ISSUE TITLE
Remove/Change Directrix

### ISSUE THREAD

**Issue by ItzaMeLuigi** [OvercastNetwork/Rotations#393]
CTF and Rage do not mix well together. All you need is one defender to stalemate the map causing attackers to constantly painloop with little to no progress. If the defender dies, they respawn next to the flag and can easily kill the runner. Removing the Rage aspect of the map would make it play a lot better.

**Comment by Ipskie** [comment]
I agree with this, Rage-CTF is generally a bad idea, similar to Rage-Anything-Else. It's a cheap gimmick to make the map more exciting because the normal version isn't exciting enough. I do however think that Directrix would work perfectly well as a non-rage CTF

**Comment by Tapetepato** [comment]
-1, most of ragectfs aré terrible, but this one is by far the most enjoyable map on Broken imo

**Comment by matic0basle** [comment]
I agree. Rage-[gamemode] is not that great. For TDM it kind of works but not for CTF. Its fast paced but to me, to some point it looks like lazy map design. Not trying to be rude or offend any map creators but theres not that much balancing with Rage-[gm] maps. No need for gameplay path design that takes a long time, quickly give it a simple layout some detail and a rage sword, boom map done without any time going directly to map design, lanes and balancing. Theres nothing to balance because of it.

Support this fully.

**Comment by DoomRobotBoy** [comment]
I disagree. Rage and CTF do work together, the combination is great for this map. CTF is fast-paced since its just a run through your enemy side to get their flag. With normal swords or bows one would never be able to kill the flag carrier when that flag carrier is already halfway there. Rage is as fast-paced and CTF and that compensates the run-in-run-out way of capturing flags.

Not to mention that Directrix has a 3.98 average rating.

**Comment by Z3R0Z3R0Z3R0** [comment]
@DoomRobotBoy Ratings for all CTF maps are really inflated right now, so 3.98 isn't as significant as it would otherwise be.

**Comment by DoomRobotBoy** [comment]
@Z3R0Z3R0Z3R0 Still, I don't see any reason to even consider removing this map. Games last a good amount of time, and feedback in game is always very positive.

**Comment by ItzaMeLuigi** [comment]
@DoomRobotBoy The matches I've played last around an hour which is way too long for an average OCN match. Most people were complaining about it taking forever. 

The gameplay itself involved three defenders that would kill you as soon as you got near the flag if you even managed to get that far. Rage maps usually have higher ratings because it's so easy to farm kills. People tend to rate matches on how it affects their stats, not by the gameplay.

**Comment by DoomRobotBoy** [comment]
@ItzaMeLuigi On that I have to agree. My past feedback may not have been that accurate as I actually remembered the map. I do often play 'longer' games on it, but from most games I play on it (and I try to catch every game of Directrix there is) the match-time is average. Its not rushed, its not over the top long, its just normal... Even though there can be a lot of defenders, I myself at least always manage to get through. Also, when you carry a flag to the center you can already tag it as capped since it will be so easy to capture it from then.

I know that maps are affected by the impact it has on their stats, though if it would actually play THAT bad I think it would be way lower then nearing the 4.00. I might be wrong though, so it'd be best to see how it goes once CTF loses the current hype.

**Comment by DoomRobotBoy** [comment]
I have to retake my above said paragraphs, I can't play any matches anymore that do not stalemate : I 

Picking up the flag is decently possible, its hard, but doable. Capturing it, is however impossible, because a defender can return faster than you can even attempt an escape.

Its probably better to edit the back part or remove this map.

**Comment by mrapple** [comment]
Sorry. This map is stalemate-y but it has a 4.03 rating. Not going to remove it when the general public seems to like it so much.

**Comment by Z3R0Z3R0Z3R0** [comment]
@mrapple Did you factor in how all ctf's have an inflated rating right now? 4.03 isn't as astounding as it would isually be, as most CTF maps are rated very highly.

In addition, shouldn't the gameplay and the way it reflects what you want from the maps on the network come before the ratings? Do you want maps that are almost always stalemated on your server?

**Comment by Ipskie** [comment]
@mrapple I think the high rating is a function of CTF novelty more than the actual map quality. Comparing it to fellow CTF maps might (or might not) give you a better idea of it's true popularity

**Comment by mrapple** [comment]
Sorry guys, but 4.0 is still on the high end for CTF maps. If the gameplay is too stale in a few weeks we'll remove it.

Also, ratings take stalemating into account. Should the map be improved? Probably, but that doesn't mean it should be removed from rotations.

**Comment by ItzaMeLuigi** [comment]
@mrapple Rating should be taken with a grain of salt. People love playing Rage type maps because it's so easy to get kills and the stalemateyness only extends the time they can use the map to killfarm. I would rather not have the map itself removed, but just the rage aspect.
