### ISSUE TITLE
Reintroducing a map

### ISSUE THREAD

**Issue by syIIzy** [OvercastNetwork/Rotations#406]
i think alpha and beta should have scorched grove added to the rotation

**Comment by Ipskie** [comment]
Please change the title to accurately fit the request. Also, scorched grove was removed for a reason, the map was huge and didn't play exceptionally well, especially considering wildly fluctuating match sizes

**Comment by Tapetepato** [comment]
Huge +1, but you should change the title and tell us your reasons on why you want it.

I feel like it should be added back, when it was in rotations it was extremely fun and it played surprisingly well. Must of the old maps that get suggested to be added to the rotations used to get rushed a lot, but this one lasted for a good time, a lot of times, even for hours. Even tought the monument A (the one in the nether themed zone) got usually rushed because of how easy it was to bridge from spawn, the other ones lasted for a while. There was iron armor, but you had to go a long way to get it, so it wasn't OP, even with the enchanted stuff, since most people could find it. 
The fact that iron and enchanted weapons were at the middle of the map made it really fun, because it encouraged pushes from the enemy team, and sometimes people dominated that zone so you had to tunnel or go with your team too and kill them. Also, this made it not difficult for attackers to get the monument C, since even tought it was somewhat near from spawn, people could get it with that, and people from spawn could kill them with their gold armor, by going to get iron armor, or just by the help of their teammates, so it wasn't either easy or difficult. There's probably more good things about this map, but since it's been so long since it was in rotations, i can't think of other things. It also looked really good, and i honestly don't know why it was removed in the first time.
It wasn't rushed like all CTW and DTC games, and it didn't lasted exaggeratedly long like The Nile, so i don't see why it shouldn't get added back to rots.

**Comment by thestrangeboy1** [comment]
#326 Let's make sure each map has only 1 issue.
