### ISSUE TITLE
Changing mini01 and mini02 rotations

### ISSUE THREAD

**Issue by Guicotsch** [OvercastNetwork/Rotations#407]
Mini02 EU is the mini CTW rotation of the server. This is, with the Capture server the most played servers but tbh this is getting boring and people are just farming wools. I'd like to re-think the way mini02 and mini03 are made.
To me, mini03 is almost perfect, it has got TDM, CTW and DTC/M maps, the issue is that recently with the low player count we never see mini03 which means we can not play miniDTC/M at all.

My idea was to change the whole rotation of mini01 and mini02 to be able to play all the gamemodes. As a whole, the mini03 rot is a good rotation but it's damn too long (30 maps to be exact). If we cut this rotation in 2 to have too independant rotations and changing some maps it can bring some fun.
As a start, I propose these rots:

**Mini01:**
- SolitudeMC
- Warlock
- Deepwind Jungle
- Aztecatti
- Aureola
- Circus DTC
- Lost World CTP
- Dynamo
- Snowy Wars
- Desert Cataract
- Battle Ecliptica II
- Levels (I do not know this one but it looked cool)
- Facility

**Mini02:**
- Sunrise Over Paradise
- Hot Dam Mini
- Cloud Nine
- Empire
- Boletum
- Banana Split
- Tebulas
- Snowy Wars
- Balloons DTM
- Cargo
- The Fenland
- Nightstail
- Battle Ecliptica II (since everyone seems to like it)

Thanks!
PS: I made a topic so a bigger part of the community can see it and think about it

**Comment by DoomRobotBoy** [comment]
I agree with you completely, a different rotation may draw a lot of players back to EU. Especially because of the current low player counts on EU, the mini's would be the best thing to focus on.

However, I suggest adding:
- Atromix
- Coastline 
- Tree of Life Mini? (was added recently and am actually quite interested in playing it; also nostalgic feelings ;)

Removing:
- Aureola (its just that in my eyes it has pretty boring gameplay)
- Nightsail

Trying out for the rotation:
- University: https://oc.tc/forums/topics/552c4ace5f35b9da6f00120f
-

**Comment by Guicotsch** [comment]
@DoomRobotBoy I made those rotations only to give a first idea of what I really wanted, of course they are not adapted and need a bit of change :)

**Comment by thestrangeboy1** [comment]
I believe the changes made in the new mini rotation update suit what you wanted.
