### ISSUE TITLE
Replace 9th Law for The 8th Law

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Rotations#414]
We played it a few minutes ago on a /sn and it played very well, monuments lengthened the match (https://oc.tc/matches/5560aa6ac8f2b76ddaf27a5f) and strats to get them were very funny.

**Comment by thestrangeboy1** [comment]
I'm not sure if we're going to want 4 objective maps in rotations. They've generally never worked well as it's too much to defend and it spreads out defenders to the point that 2 or 3 are rushed within 5 minutes. Monuments are really high up and too easy to defend to the point that skybridges are generally the way to break it as the player flow out of spawn intersects the lane towards the monument. I think it's better if we stick to the CTW version, even though it probably won't stick around due to low ratings.

**Comment by 2000thehecf1** [comment]
@thestrangeboy1 Oh, I completely forgot about this. Why was never 9th Law added back to rots? It was removed due to a bug with the woolroom dispensers, but the bug was fixed a while ago and the map hasn't been added back.

**Comment by thestrangeboy1** [comment]
Hmm, I was unaware about it not being back in. I'll get it back in tomorrow.

**Comment by 2000thehecf1** [comment]
@thestrangeboy1 Okay, thank you!
