### ISSUE TITLE
Remove Citadel

### ISSUE THREAD

**Issue by Tapetepato** [OvercastNetwork/Rotations#433]
Citadel is a mini Attack/Defend Capture The Wool map. It looks good, but it's gameplay was never good since the first time it was tested, and i don't see why it even got added to the rotations in first place. The gameplay is just not fun, and the matches are usually the same.
If you are going to make a map dedicated to defend, at least make it possible to defend. The woolroom  is in the middle of the base, with a void gap and then a lot of land surrounding it. You can't defend this, and people don't know what to do. The woolroom punch bows are too powerful and they shouldn't be added on a mini map. When "defending" you will see that the attackers can only painloop until they get it. There is absolutly nothing to do in the map except for walking around and under the wall to kill attackers, if you are a defender. The 30 seconds timer is useless and it doesn't change anything at all.
It's too easy to get into the defenders side, when you can pillar up the wall, or tunnel, and with the TNT it's even easier to get past enemies, that, and the fact that you can run around and fast-bridge into the woolroom extremly easily.
When as a defender, you are trying to stop an enemy from getting out of the woolroom, they will just run faster than you and go out from another side. When you follow an attacker with the wool, you won't be able to stop him because at the moment you get to the beach you get spammed with the "you can't get close to the enemy base!!!!" message, that is completly unnecessary, since you can't spawnkill or anything like that in here. The tents and trees are just a mess and the way out the defenders place is too short, so you most likely wont stop any attacker with the wool at the moment they get past the wall.

Maybe, just maybe, this map would work as a DTM or even as a CTF, but as a CTW, it just doesn't play well.

**Comment by matic0basle** [comment]
I will have to disagree with this. The map is nice, pretty balanced and the gameplay is good. It deserves to be on the rotations.

Its quite possible to defend it and it can also be really easy to do. You shouldn't defend the wool room. If you plan on that it won't be successful. You need to defend the whole top side and not let them get to the top otherwise it will be hard to defend but thats good. If you let them get up there then you will have trouble.

The 30 second timer isn't useless. It lets defenders take possitions before attackers are released.

>When as a defender, you are trying to stop an enemy from getting out of the woolroom

You shouldn't let them get in it in the first place.

I don't think the map should be removed as after a lot of matches I haven't noticed any issues. The map might need a bit of getting used to but other than that it seems pretty balanced. It might be a map more for setnexting but ATM I think its fine.

**Comment by Diamyx** [comment]
I disagree with all of this, so I'm just going to point some things out.

> If you are going to make a map dedicated to defend, at least make it possible to defend.

It's entirely possible to defend, it's just not your typical way that you do on every map. You're not supposed to circle around the entire wool room with a wall/pit or whatever, you're supposed to defend the majority of the lane. Here's an example of a decent defense that gets the job done for the most part:  http://i.imgur.com/7iuqOgh.png . It covers the entire lane, and as long as defenders spread out, they should be fine. It was built in ~3-4 minutes by one person alone, imagine what multiple people could do.

> The woolroom punch bows are too powerful and they shouldn't be added on a mini map.

I agree that punch bows shouldn't be added to a mini map, but I think Citadel is wide enough and it doesn't have that much void to make punch overpowered.

> There is absolutly nothing to do in the map except for walking around and under the wall to kill attackers

Isn't that what defending is all about? Protecting the objective? Of course you're going to patrol around the whole top area of the map and watch out for attackers. If you're not doing that, you could be building a defense. As for attackers, they have a few ways to attack. They can sneak around the edges, tunnel, sky bridge, go up the waterfall, get kills and use TNT to get into the defenders' area.

> The 30 seconds timer is useless and it doesn't change anything at all.

Defenders need some time to get into position and build an initial, simple defense. The spawn timer does just that, and it was deemed necessary after the first few tests.

Now regarding the last paragraph about capping the wool. Attackers can't outrun you when running out of the wool room; they're not faster as you claim, they get slowness. The "you can't get close to the enemy base!!!!" region is there because of a couple reasons: First off, it used to be possible to shoot into the ship, and it was incredibly annoying, as attackers couldn't get out of their spawn. Second, if you let an attacker run that far out that he reaches his spawn, there's no way you're going to be able to get him in the last few seconds before he gets to the wool monument anyway.

From what I've seen, the map is fairly balanced. There's a nice mix of victories for both the attackers and the defenders.

**Comment by Tapetepato** [comment]
When you follow someone into the beach, there is still 20+ blocks of water that they need to travel, so if you could step on the sand at least, it would be easier.
By "a mess" i meant that they are just a lot of things and it's difficult to chase someone. 
When i said that there's nothing to do i meant that you can only watch but can't really build an effective defense, and they usually find a way since the lane is huge and they can do all the stuff that you said while defenders just wait and hope that attackers can't run a couple of blocks and fastbridge.

I like the map and it looks great, but as i said, it would fit better as another gamemode, or even change it a little bit to make it so both teams do both things. Also, it would be nice if defenders had a
TNT killreward too.

**Comment by matic0basle** [comment]
>By "a mess" i meant that they are just a lot of things and it's difficult to chase someone. 

It should be difficult to chase someone and not let you get an easy kill. That IMO is good. It shouldn't be impossible but its not, saying from experience.

> it would fit better as another gamemode,

I don't know. I think it fits CTW the best with the layout it has ATM.

**Comment by Tapetepato** [comment]
Yup you are right, it's entirely possible to defend, see here the results of the game i defended just now, just like in the picture you showed me.
https://oc.tc/matches/558d9d9bc8f2d1265ed4b631

**Comment by Oo-TheFrog** [comment]
+1 Its the worst rated CTW map in the mini rotations.

**Comment by Oo-TheFrog** [comment]
The last update seems to have fixed most of these issues.

**Comment by thestrangeboy1** [comment]
Last update has improved ratings and has made defenders win roughly half of the time when the team sizes are reasonably full. The map was designed to give defenders a nice chokepoint to work with and have a void gap around the wool as a safety net for those who get by. Offenders have several ways of attacking which makes the map unique.
