### ISSUE TITLE
Remove the grove from CTF

### ISSUE THREAD

**Issue by amactus** [OvercastNetwork/Rotations#434]
I find this map plays really badly because the flag person just stays below spawn and is surrounded by other players.

**Comment by TheMolkaPL** [comment]
So KotF works..., but yeah... it's to hard to get the flag back.

**Comment by kroest** [comment]
i dont really like this map too, i feel like concourse is a way better kotf map.

**Comment by Tapetepato** [comment]
I like it, but i feel like the respawntimer is too long

**Comment by TheMolkaPL** [comment]
^^ This preverts people from defending

**Comment by DoomRobotBoy** [comment]
I've been avoiding The Grove for the past weeks, but now that I played it I wanted to jump in the discussion as well. 

The map isn't that bad to being with. Its just very repetitive gameplay with some very confusing and plain bad things on the side. Its always the same story: player picks up flag, sits in spawn pool sometimes for an entire game until they win. And even before there was a spawn pool these events kept occurring again and again. The spawn drop is also incredibly long, and I kinda find it a cheap way to solve the problem of the hard-to-get flag carriers (even tho it doesn't solve it).

My first impressions of the map were that mobility was central, that you could run around with an elite group and your flag carrier and keep the match going, just like concourse. But everyone just camps right out of spawn (so reinforcements can come easier) and the outer corners of the map are therefore not even used. I think that if you would take this map, theme, idea, and make it bigger and a flag blitz, that it would play better. Everyone will otherwise always camp closest to spawn (unless you make spawn as dangerous as on concourse).

I would rather see this improved than removed, but i don't think it can get improved so fast (cuz pbat is busy i think).

**Comment by Electroid** [comment]
Was updated to address the issues recently.
