### ISSUE TITLE
Add Parallax to Ranked

### ISSUE THREAD

**Issue by orky48** [OvercastNetwork/Rotations#454]
So far 4 people agree with me.

"It's better than Directrix so yeah" - doom

and

"Is this a joke" - jig
"Is a Directrix a joke?" - doom
"Yes" - jig
"There we go" - doom

and 

"I will support you all the way" -halfmaster

and

[14:34:14] (Channel) LArrowHead: change my vote to +1

So that means 5/5 people want parallax into the ranked rots that is like 100%. And a great sample base

Pros: 
        - 100% like
        - I know how to easily win
        - It is different 
Cons:
        - 0% dont like

In my opinion you should add it now.

*I personally have never played Directrix so i dont know if parallax is better than it just going of what others said

**Comment by gilrosenthal** [comment]
I support 10/10

**Comment by Oo-TheFrog** [comment]
+1 Easy map to defend on.

**Comment by orky48** [comment]
mapdevs please look at the forum thread https://oc.tc/forums/topics/55dc6ca3c296359edf000886

**Comment by CoWinkKeyDinkInc** [comment]
There's a ton of stuff to do in Parallax, and I think it would be great to see this map and some others with the same concept. The only problem is that a 30 minute time-limit might not be enough to fully complete the game in an average time.

I think that more maps like Parallax should be made, the theme and how stuff is done is new.  What was that other map like that?  It was a DTC or DTM with mob-spawners where the two lanes connect.

**Comment by thestrangeboy1** [comment]
I don't think having a map with a random chance of a mob dropping wool would be good to have on Ranked when so many people care about their stats. There's one place to sword and the void gap is huge which makes it hard to shoot people and even if you shoot them a few times, they probably won't die because there's a huge amount of iron/diamond supply on the map. The map is way too big for 10v10 ranked scenario and it was NOT designed to be a competitive map with organized teams.
