### ISSUE TITLE
Add Broken Unity

### ISSUE THREAD

**Issue by 2000thehecf1** [OvercastNetwork/Rotations#465]
I know it's a very old map and it got removed more than one year ago from rots but I don't know why. Ok it sometimes get rushed as every map does but it can bring some long matches too (https://oc.tc/matches/55f38e69c8f23274a077a281, https://oc.tc/matches/55b3bcd9c8f21292c72ae0f0, https://oc.tc/matches/55cedcb2c8f21b521314914a) and, imo, it's a very fun map to play.

**Comment by thestrangeboy1** [comment]
Maps that are set next tend to be defended more so of course this will have longer match times than it previously had in rotations. It's very hard to defend a void gap in front of a wool room and everyone spawns in leather armor so it's easy to painloop across the huge void gap in which people only cross from those circle islands with power bows or diagonal in the middle. The map is so huge that it allows offenders to run for a long time and not get cornered easily. The victory monument being on the enemy team's side is confusing for a lot of players and it doesn't bring much of a challenge than running back to your side which should be easy enough with the amount of space offenders have to work with. It has a horrible rating of 3.43 and if you look at the match times on the map page you can clearly see how easy it is to rush because on average those matches last 4-6 minutes. Chances are the map will still be rushed when added back to the rotation.
