### ISSUE TITLE
Update Micro Rotation 

### ISSUE THREAD

**Issue by GoldenOre** [OvercastNetwork/Rotations#500]
Remove: 

Destiny - Gameplay sucks since the map is so hilly. 
Guarded Coast KoTF - Imo this map just isn't fun. Its a huge map for 5 players, once you land on the ground it could take a while to get back up into the air, and when the flag carrier dies its easy for him to just fly back down and get the flag again since he spawns in the air.

Add:

Geiran - Looks great and plays pretty good.
I tested/developed the following 3 while I had map residence and they play pretty good.
Mesa 5x5 - Has some unique horse pvp.
Pompeii 
Pirate Cove

There are probably more maps that could be added but I haven't played them. 

Edited: 

Just tested The Snowmelt Mines and it plays pretty good so it could also probably be added.

**Comment by mitchiiii** [comment]
I think that Retro KoTF needs to be removed the most, for all the same reasons you stated for Guarded Coast. Unlike Guarded Coast, players don't have double jump, which makes it incredibly difficult to get back into the air, and with more than half of the jump pads slamming you into the plants, you have little option but to run around clueless on the ground. Retro KoTF is also open and large, making it challenging to get anywhere efficiently in all honesty.
Scoring for both Retro KoTF and Guarded Coast KoTF need to be re-balanced, as currently you can grab the flag and be top of the leader board within seconds because of the rapid score rate and the fact that no one can actually hit you.
All the maps suggested to add look like they would work fine in rotations. I'd also like to see Decay, Stonehenge, Stagnant Waters, and possibly Rage Quit (5x5 edit). I haven't yet played the Rage Quit edit, but I would expect it to play considerably well.

**Comment by GoldenOre** [comment]
Sounds good

**Comment by samthecat** [comment]
https://oc.tc/forums/topics/5786e14e67d52216b700004b?page=1#5786e14e67d52216b700004d
