### ISSUE TITLE
Add SSB TE to Ranked

### ISSUE THREAD

**Issue by MrTheSharpie** [OvercastNetwork/Rotations#511]
Ranked rotation feels like it's lacking Destroy maps, and SSB is a classic. If I am not mistaken, TE plays better than the average SSB for ranked, but if that's not the case just add the normal one. Right now the only DTC/M map in the rot is fractal.

**Comment by pj1210** [comment]
Agreed.

**Comment by thestrangeboy1** [comment]
SSB may be a classic but the map has too many roles for players to commit to. People icarus rush the supplies within the first 5 minutes because nobody waters them nor do people chase the offenders as they would rather stick to cannoning an already watered ship. SSB is easier to water than SSB TE and it still has the problems of people rushing it and destroying almost all the resources. Not to mention defending those antennas without any instant backup is very difficult to manage and you wouldn't even have a good defense by the time they get rid of over half of the monument. A map like fractal is better than SSB because of the lack of roles your team will need to commit to, it's 2 monuments, 1 core and the TNT room with some cannoning you can do to the lanes. SSB is meant for high level competitive, not semi-competitive (ranked).
